[package]
name = "json-formatter"
authors = ["Dervex"]
description = "Custom serde JSON formatter"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
ryu = "1.0.20"
serde_json = "1.0.117"
